### PR TITLE
Issue1 copy edits

### PR DESCRIPTION
**Pull request by nevanscott**

### CODE REVIEW

**Comment by rebeccarubenstein** [comment]
@nevanscott  The cite tags weren't pulling in, which is why I used italics tags. I'll fix this and also the Markdown on the links. Are there any other tags I might be misusing that you can let me know about? So I can get it right the first time?

**Comment by nevanscott** [comment]
I think it was just those that I noticed right now. The `<cite>` tags may not show in the preview on github, even though they work on the actual site.

**Comment by rebeccarubenstein** [comment]
@nevanscott Just wanted to let you know I updated the Markdown on the Wendy piece.

**Comment by nevanscott** [comment]
Thanks!

**Pull request merged**
